baseURL = 'https://example.org/'

languageCode = 'fr-ca'
title = '420-ZG4-MO Linux'
theme = 'hugo-theme-relearn'

[params]
    disableLandingPageButton = true
    disableSearch = true
    disableHomeButton = true
    # Change default color scheme with a variant one.
    themeVariant = "blue"


  [params.menu]
    alwaysopen = false

[module]
  [[module.imports]]
    path = 'github.com/McShelby/hugo-theme-relearn'

[mediaTypes]
  [mediaTypes."text/javascript"]
    suffixes = ["js"]

[outputFormats]
  [outputFormats.print]
    name= "print"
    baseName = "index.print"
    isHTML = true
    mediaType = 'text/html'
    permalinkable = false
    noUgly = true

  [outputFormats.search]
    name= "search"
    baseName = "index.search"
    isPlainText = true
    mediaType = 'text/javascript'
    permalinkable = false
    noUgly = true

  [outputFormats.searchpage]
    name= "searchpage"
    baseName = "search"
    isHTML = true
    mediaType = 'text/html'
    permalinkable = false
    noUgly = true

[params.relearn.dependencies]
  [params.relearn.dependencies.mathjax]
    name = "MathJax"
  [params.relearn.dependencies.mermaid]
    name = "Mermaid"
  [params.relearn.dependencies.openapi]
    name = "OpenApi"

[languages]
  [languages.en]
    [languages.en.params]
      landingPageName = "<i class='fa-fw fas fa-home'></i> Home"


